#spring.application.name=UserManagementService


server:
  port: 20001

spring:
  application:
    useOTP: false
    otpProd: false
    otpTestMail: mailto:tkilunda@emtechhouse.co.ke
    name: USER-MANAGEMENT-SERVICE
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  jpa:
    hibernate:
      ddl-auto: update
      #use-new-id-generator-mappings: false
    show-sql: false

    properties:
      hibernate:
        format_sql: true
  #        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

  datasource:

    #
    url:  jdbc:mariadb://localhost/OnlineShopper
    username: root
    password:

    #    url:  jdbc:mariadb://52.15.152.26:3306/muumini
    #    username: emtech
    #    password: emtech@2022




driverClassName: org.mariadb.jdbc.Driver



users:
  app:
    jwtSecret: /buCOEjS/+H7ZwekxyLKLdDeegHUGEytjxuivosdrzjRG4g4E+kA3uXO5lvGBVsl2NwqsgiGUUI5bjgY/6WG/VSIIG+22b1Rvdb59BY0YRod6Dnjnp0REsPn//hshs6ucnOVCBRp0lbVb1kP+EDOM7W7N72/+t+R1d8JQ4pjisoJZI4e0MV3PlZtzXKI0SY2EQUtI
    jwtExpirationMs: 43200000

    client:
      origin: http://localhost:4200/

#Swagger Config
springdoc:
  swagger-ui:
    path: /api-docs  # Set a custom path for Swagger UI (optional)
    configurationUrl: "http://localhost:9095/api-docs"

#Eureka Config
#Do this after adding the eureka-netflix dependencies to every microservice
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka # URL of your Eureka Server


#UserManagementService:
#  feign:
#    client:
#      config:
#        default:
#          loggerLevel: full
